CREATE TABLE recommendation_model_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  model_name VARCHAR(120) NOT NULL,
  model_version VARCHAR(120) NOT NULL UNIQUE,
  algorithm VARCHAR(60) NOT NULL,
  artifact_path TEXT,
  status VARCHAR(30) NOT NULL,
  trained_from TIMESTAMPTZ,
  trained_to TIMESTAMPTZ,
  metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  feature_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by BIGINT REFERENCES users(id),
  activated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_recommendation_model_versions_status CHECK (status IN ('CANDIDATE', 'SHADOW', 'ACTIVE', 'RETIRED', 'FAILED'))
);

CREATE INDEX idx_recommendation_model_versions_status ON recommendation_model_versions(status);
CREATE INDEX idx_recommendation_model_versions_created_at ON recommendation_model_versions(created_at);
CREATE INDEX idx_recommendation_model_versions_deleted_at ON recommendation_model_versions(deleted_at);

CREATE TABLE recommendation_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  created_by_admin_id BIGINT REFERENCES users(id),
  event_type VARCHAR(50) NOT NULL,
  label_score NUMERIC(6, 2) NOT NULL,
  source_surface VARCHAR(80) NOT NULL,
  recommendation_id VARCHAR(160),
  build_id BIGINT REFERENCES builds(id),
  part_id BIGINT REFERENCES parts(id),
  as_ticket_id BIGINT REFERENCES as_tickets(id),
  model_version_id BIGINT REFERENCES recommendation_model_versions(id),
  category VARCHAR(50),
  rank_position INTEGER,
  idempotency_key VARCHAR(180),
  event_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_recommendation_events_type CHECK (
    event_type IN (
      'IMPRESSION',
      'CLICK',
      'DETAIL_VIEW',
      'SAVE',
      'CHANGE_ADOPTED',
      'ADD_BUILD_TO_DRAFT',
      'ORDER_INTENT',
      'REJECT',
      'CHANGE_REVERTED',
      'AS_CONFIRMED_NEGATIVE'
    )
  ),
  CONSTRAINT chk_recommendation_events_category CHECK (
    category IS NULL OR category IN ('CPU', 'GPU', 'RAM', 'MOTHERBOARD', 'STORAGE', 'PSU', 'CASE', 'COOLER')
  ),
  CONSTRAINT chk_recommendation_events_rank_position CHECK (rank_position IS NULL OR rank_position >= 0)
);

CREATE INDEX idx_recommendation_events_user_created_at ON recommendation_events(user_id, created_at);
CREATE INDEX idx_recommendation_events_type_created_at ON recommendation_events(event_type, created_at);
CREATE INDEX idx_recommendation_events_part_id ON recommendation_events(part_id);
CREATE INDEX idx_recommendation_events_build_id ON recommendation_events(build_id);
CREATE INDEX idx_recommendation_events_as_ticket_id ON recommendation_events(as_ticket_id);
CREATE UNIQUE INDEX ux_recommendation_events_user_idempotency
  ON recommendation_events(user_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE TABLE recommendation_shadow_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES users(id),
  model_version_id BIGINT REFERENCES recommendation_model_versions(id),
  source_surface VARCHAR(80) NOT NULL,
  request_hash VARCHAR(80) NOT NULL,
  candidate_type VARCHAR(30) NOT NULL,
  candidate_id VARCHAR(180) NOT NULL,
  part_id BIGINT REFERENCES parts(id),
  score NUMERIC(12, 6) NOT NULL,
  rank_position INTEGER,
  features JSONB NOT NULL DEFAULT '{}'::jsonb,
  raw_response JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_recommendation_shadow_scores_candidate_type CHECK (candidate_type IN ('BUILD', 'PART')),
  CONSTRAINT chk_recommendation_shadow_scores_rank_position CHECK (rank_position IS NULL OR rank_position >= 0)
);

CREATE INDEX idx_recommendation_shadow_scores_model_created_at ON recommendation_shadow_scores(model_version_id, created_at);
CREATE INDEX idx_recommendation_shadow_scores_user_created_at ON recommendation_shadow_scores(user_id, created_at);
CREATE INDEX idx_recommendation_shadow_scores_candidate ON recommendation_shadow_scores(candidate_type, candidate_id);
